### ISSUE TITLE
Issue accessing crash tracker details within Squash

### ISSUE THREAD

**Issue by Z2william** [SquareSquash/web#21]
Currently, we are experiencing an issue where "rspec spec" is returning 5 errors, and we are unable to access the bug details page in what seems to be a related issue. 

The main issue is that we get a "undefined method `[]=' for nil:NilClass" when we have received a bug in squash, and are attempting to click the bug in order to view the details. We've shown that we're getting to line 310 in app/views/layouts/application.html.rb where the raw ERB file (app/views/bugs/show.js.erb) is being converted into javascript, and then it dies within that function.

The current machine setup is OSX 10.8.2 using RVM with ruby 1.9.2-p320 and 1.9.3-p362. The scenarios tested have been with personal repos and using the sample shown in the video on the squash.io page (installing an error in the squash server and then sending the error to a full squash server). I have sent crashes from the ruby, ruby on rails, and ios versions of the client and they all encounter the same issue when clicking the bug for additional details. All the bugs successfully appear in the database and are displayed on the local Squash server GUI.

It seems like there may be a configuration issue that may need to be checked for, given that rspec does not complete 100%. I would appreciate any possible advice in system setup or other possible scenarios to investigate. This was tested on master as of 1-23-13, and tested against SHA eac1de2. I could not test against the initial commit (73e9571) due to therubyracer issue that was fixed in eac1de2.

The actual error reported on access:

```
ActionView::Template::Error (undefined method `[]=' for nil:NilClass):
    1: 
    2: 
    3: # Copyright 2012 Square Inc.
    4: #
  app/views/layouts/application.html.rb:310:in `inline_javascript'
  app/views/layouts/application.html.rb:148:in `block in body_portion'
  app/views/layouts/application.html.rb:135:in `body_portion'
  app/views/layouts/application.html.rb:27:in `block in content'
  app/views/layouts/application.html.rb:25:in `content'
  app/views/bugs/show.html.rb:1:in `_app_views_bugs_show_html_rb__1634622433784757136_70354261740560'
  app/controllers/bugs_controller.rb:184:in `show'
```

The errors reported by rspec:

```
  1) BugsController#show [authenticated] should set duplicate_of_number
     Failure/Error: get :show, polymorphic_params(@bug, false)
     ActionView::Template::Error:
       undefined method `[]=' for nil:NilClass
     # (erb):46:in `inline_javascript'
     # ./app/views/layouts/application.html.rb:310:in `inline_javascript'
     # ./app/views/layouts/application.html.rb:148:in `block in body_portion'
     # ./app/views/layouts/application.html.rb:135:in `body_portion'
     # ./app/views/layouts/application.html.rb:27:in `block in content'
     # ./app/views/layouts/application.html.rb:25:in `content'
     # ./app/views/bugs/show.html.rb:1:in `_app_views_bugs_show_html_rb__3920424542436900343_70292377150420'
     # ./app/controllers/bugs_controller.rb:184:in `show'
     # ./spec/controllers/bugs_controller_spec.rb:175:in `block (4 levels) in <top (required)>'

  2) DeployFixMarker should mark the appropriate bugs as fix_deployed
     Failure/Error: DeployFixMarker.perform deploy.id
     NoMethodError:
       undefined method `[]=' for nil:NilClass
     # ./lib/workers/deploy_fix_marker.rb:49:in `any?'
     # ./lib/workers/deploy_fix_marker.rb:49:in `perform'
     # ./lib/workers/deploy_fix_marker.rb:31:in `perform'
     # ./spec/lib/deploy_fix_marker_spec.rb:34:in `block (2 levels) in <top (required)>'

  3) DeployFixMarker should create events for the fixed bugs
     Failure/Error: DeployFixMarker.perform deploy.id
     NoMethodError:
       undefined method `[]=' for nil:NilClass
     # ./lib/workers/deploy_fix_marker.rb:49:in `any?'
     # ./lib/workers/deploy_fix_marker.rb:49:in `perform'
     # ./lib/workers/deploy_fix_marker.rb:31:in `perform'
     # ./spec/lib/deploy_fix_marker_spec.rb:50:in `block (2 levels) in <top (required)>'

  4) OccurrencesWorker#perform [distributed projects] should create a new bug if the occurrence is associated with a different deploy
     Failure/Error: DeployFixMarker.perform(d3.id)
     NoMethodError:
       undefined method `[]=' for nil:NilClass
     # ./lib/workers/deploy_fix_marker.rb:49:in `any?'
     # ./lib/workers/deploy_fix_marker.rb:49:in `perform'
     # ./lib/workers/deploy_fix_marker.rb:31:in `perform'
     # ./spec/lib/occurrences_worker_spec.rb:237:in `block (4 levels) in <top (required)>'

  5) OccurrencesWorker#perform [hosted projects] should reopen a bug only at the proper times
     Failure/Error: DeployFixMarker.perform(d.id)
     NoMethodError:
       undefined method `[]=' for nil:NilClass
     # ./lib/workers/deploy_fix_marker.rb:49:in `any?'
     # ./lib/workers/deploy_fix_marker.rb:49:in `perform'
     # ./lib/workers/deploy_fix_marker.rb:31:in `perform'
     # ./spec/lib/occurrences_worker_spec.rb:298:in `block (4 levels) in <top (required)>'
```
